


#' Example Data: haplotypes
#'
#' The haplotype pool from SKAT package, with 10,000 haplotypes and 3845 bp.
#' Haplotype dataset generated by COSI with mimicking linkage disequilibrium (LD)
#' structure of European ancestry.
#'
#' @format ## `haplotypes`
#' This list object contains the following objects:
#' \describe{
#'   \item{Haplotype}{Haplotype a numeric matrix of 10,000 haplotypes
#'   over 200k BP region. Each row represents a different haplotype,
#'   and each column represents a different SNP marker. It is generated
#'   by the calibration coalescent model (COSI) with mimicking LD structure
#'   of European ancestry.}
#'   \item{SNPInfo}{A dataframe with 3845 SNPs and 7 columns SNP infromation,
#'   where the columns mean "SNP","CHROM","CHROM_POS","ALLELE1","FREQ1","ALLELE2",
#'   "FREQ2"}
#' }
#'
"haplotypes"




